# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "CrystalSkulls"
	config.vm.box_url = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.1/vagrant-centos-7.1.box"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.network :forwarded_port, guest:8080, host:48080
	config.vm.network :forwarded_port, guest: 3001, host: 3001
	config.vm.provision :shell, :path => "provision.sh"
end
